project:
  type: book

book:
  title: "Calculo_Diferencia_e_Integral"
  author: "Norah Jones"
  date: "4/23/2026"
  chapters:
    - index.qmd
    - intro.qmd
    - c01.qmd
    - c02.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

